version: "3.9"

services:
  ticket-service:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - opsmind-net
    restart: unless-stopped

networks:
  opsmind-net:
    external: true